### PR TITLE
Bug fixes

### PR DESCRIPTION
**Pull request by chrisprosan**
Includes bug fixes for API and some instructor pages (view_goal and add_member).

### CODE REVIEW

**Comment by Prerna0822** [comment]
Everything is working fine.

**Review by Prerna0822 — APPROVED** [review]
Testing done for backend pages. Bugs are fixed now.

**Review by ASingh368 — APPROVED** [review]
add students appears to work, as well as the other buttons

**Comment by chrisprosan** [comment]
added fix for header and session warnings

**Pull request merged**
