### PR TITLE
Last pr before demo (hopefully)

### PR DESCRIPTION
**Pull request by chrisprosan**

### CODE REVIEW

**Review by maxwellsterling — APPROVED** [review]
Can no longer access the home page or viewCourse page thru just the url.

**Review by Prerna0822 — APPROVED** [review]
Bugs have been fixed. Works fine now.

**Comment by chrisprosan** [comment]
typo in commit f33dbf1. i actually meant process_delete

**Review by ajytan — APPROVED** [review]
Tested the bug fixes and bugs have been fixed.

**Review by ASingh368 — APPROVED** [review]
changes have been tested and are ready to merge

**Pull request merged**
